using DocumenterVitepress

# Whether this tag is the newest release, and so owns the `stable` alias.
#
# Julia parses Python-style prerelease tags such as v2.0.0a2 as v2.0.0-a2, and
# determine_bases then reports the alpha as owning the v2.0.0 release folder, so only
# plain release tags reach it.
function claims_stable(subfolder; kwargs...)
    occursin(r"^v\d+(\.\d+){0,2}$", subfolder) || return false
    return "stable" in DocumenterVitepress.determine_bases(subfolder; keep = :patch, kwargs...)
end

function stable_redirect_files(page_names, stable_version)
    pages = sort(filter(page -> page ∉ ("index", "404"), page_names))
    files = Dict(
        "stable/index.html" => """<!--This file is automatically generated by docs/deploy.jl-->
<meta http-equiv="refresh" content="0; url=../$(stable_version)/"/>
""",
    )
    for page in pages
        files["stable/$(page).html"] = """<!--This file is automatically generated by docs/deploy.jl-->
<meta http-equiv="refresh" content="0; url=../$(stable_version)/$(page).html"/>
"""
        files["$(page).html"] = """<!--This file is automatically generated by docs/deploy.jl-->
<meta http-equiv="refresh" content="0; url=stable/$(page).html"/>
"""
        files["$(page)/index.html"] = """<!--This file is automatically generated by docs/deploy.jl-->
<meta http-equiv="refresh" content="0; url=../stable/$(page).html"/>
"""
    end
    return files
end
