using Documenter
using DocumenterVitepress

# Layout object that Documenter dispatches on. DocumenterVitepress's own BaseVersion
# lists prereleases in the version picker and resolves a folder's version only through
# siteinfo.js.
struct PySRVersions
    base::String
end

const RELEASE_FOLDER = r"^v\d+(\.\d+){0,2}$"

Documenter.determine_deploy_subfolder(deploy_decision, ::PySRVersions) = nothing

# Julia parses Python-style prerelease tags such as v2.0.0a2 as v2.0.0-a2, so
# passing them upstream would alias them onto the release folder.
function deploy_bases(
    subfolder;
    all_tagged_versions = DocumenterVitepress.get_all_tagged_release_versions(),
)
    return occursin(RELEASE_FOLDER, subfolder) ?
        DocumenterVitepress.determine_bases(
            subfolder;
            keep = :patch,
            all_tagged_versions,
        ) : [subfolder]
end

function folder_version(root, folder)
    try
        siteinfo = read(joinpath(root, folder, "siteinfo.js"), String)
        version_match = match(r"DOCUMENTER_CURRENT_VERSION\s*=\s*\"([^\"]+)\"", siteinfo)
        return VersionNumber(version_match.captures[1])
    catch
        try
            return VersionNumber(folder)
        catch
            return v"0.0.0"
        end
    end
end

function Documenter.postprocess_before_push(
    versions::PySRVersions;
    subfolder,
    devurl,
    deploy_dir,
    dirname,
)
    # `deploy_dir` is the gh-pages root joined with the base, and the base may itself be
    # nested, as in previews/PR123
    root = deploy_dir
    for _ in splitpath(versions.base)
        root = Base.dirname(root)
    end
    folders = filter(readdir(root)) do folder
        isdir(joinpath(root, folder)) &&
            (folder == "stable" || folder == devurl || occursin(RELEASE_FOLDER, folder))
    end
    version_folders = filter(folder -> occursin(RELEASE_FOLDER, folder), folders)
    named_folders = setdiff(folders, version_folders)
    sort!(version_folders; by = folder -> folder_version(root, folder), rev = true)

    versions_file = joinpath(root, "versions.js")
    open(versions_file, "w") do io
        println(io, "var DOC_VERSIONS = [")
        for folder in [named_folders; version_folders]
            println(io, "  $(repr(folder)),")
        end
        println(io, "];")
        if !isempty(version_folders)
            println(io, "var DOCUMENTER_NEWEST = $(repr(string(folder_version(root, first(version_folders)))));")
        end
        if "stable" in named_folders
            println(io, "var DOCUMENTER_STABLE = \"stable\";")
        end
    end
    print(read(versions_file, String))

    if "stable" in named_folders
        write(
            joinpath(root, "index.html"),
            """<!--This file is automatically generated by docs/deploy.jl-->
<meta http-equiv="refresh" content="0; url=./stable/"/>
""",
        )
    end
end
