using DocumenterVitepress

# Whether this tag is the newest release, and so owns the `stable` alias.
#
# Julia parses Python-style prerelease tags such as v2.0.0a2 as v2.0.0-a2, and
# determine_bases then reports the alpha as owning the v2.0.0 release folder, so only
# plain release tags reach it.
function claims_stable(subfolder; kwargs...)
    occursin(r"^v\d+(\.\d+){0,2}$", subfolder) || return false
    return "stable" in DocumenterVitepress.determine_bases(subfolder; keep = :patch, kwargs...)
end

const STUB_MARKER = "<!--This file is automatically generated by docs/deploy.jl-->"

# Directories at the root of gh-pages that a `stable` deployment must never rewrite.
const PRESERVED_ROOT_DIRS = (".git", "previews", "stable")

redirect_stub(target) = """$(STUB_MARKER)
<meta http-equiv="refresh" content="0; url=$(target)"/>
"""

# Page paths are URL-relative and may be nested, so every stub has to climb back to the
# root before naming its target.
climb(depth) = repeat("../", depth)
depth_of(path) = count(==('/'), path)

function add_stub!(files, path, target)
    haskey(files, path) && error("Conflicting redirect stubs for $path")
    files[path] = redirect_stub(target)
    return files
end

function stable_redirect_files(page_paths, stable_version)
    pages = sort(filter(page -> page != "index" && basename(page) != "404", page_paths))
    files = Dict("stable/index.html" => redirect_stub("../$(stable_version)/"))
    for page in pages
        depth = depth_of(page)
        add_stub!(
            files,
            "stable/$(page).html",
            "$(climb(depth + 1))$(stable_version)/$(page).html",
        )
        add_stub!(files, "$(page).html", "$(climb(depth))stable/$(page).html")
        # A page that is already a directory index has no separate directory form.
        basename(page) == "index" && continue
        add_stub!(files, "$(page)/index.html", "$(climb(depth + 1))stable/$(page).html")
    end
    return files
end

# Every `.html` file below `dist`, named the way its URL is, so nested pages get stubs.
function built_pages(dist_dir)
    pages = String[]
    for (directory, _, files) in walkdir(dist_dir), file in files
        endswith(file, ".html") || continue
        push!(pages, splitext(relpath(joinpath(directory, file), dist_dir))[1])
    end
    return sort(pages)
end

# Stubs left at the root by earlier deployments for pages that no longer exist. Only
# files carrying the marker are candidates, so version folders and hand-written pages are
# never touched, and `stable` is skipped because its deployment replaces it wholesale.
function stale_root_stubs(root, current_paths)
    stale = String[]
    for (directory, directories, files) in walkdir(root)
        relative = relpath(directory, root)
        relative == "." && filter!(!in(PRESERVED_ROOT_DIRS), directories)
        for file in files
            endswith(file, ".html") || continue
            path = relative == "." ? file : joinpath(relative, file)
            path in current_paths && continue
            startswith(read(joinpath(root, path), String), STUB_MARKER) &&
                push!(stale, path)
        end
    end
    return sort(stale)
end
