using Test

include(joinpath(@__DIR__, "deploy_versions.jl"))

@testset "stable ownership" begin
    tags = [v"2.1.0", v"2.0.0", v"1.5.10"]

    @test claims_stable("v2.1.0"; all_tagged_versions = tags, log = false)
    @test !claims_stable("v2.0.0"; all_tagged_versions = tags, log = false)
    # determine_bases would report this alpha as owning v2.0.0
    @test !claims_stable("v2.0.0a2"; all_tagged_versions = tags, log = false)
    @test !claims_stable("dev"; all_tagged_versions = tags, log = false)
    @test !claims_stable("previews/PR123"; all_tagged_versions = tags, log = false)
end

@testset "stable redirects" begin
    pages = ["index", "examples", "404", "api"]
    files = stable_redirect_files(pages, "v2.2.1")

    @test files["api.html"] == """<!--This file is automatically generated by docs/deploy.jl-->
<meta http-equiv="refresh" content="0; url=stable/api.html"/>
"""
    @test files["api/index.html"] == """<!--This file is automatically generated by docs/deploy.jl-->
<meta http-equiv="refresh" content="0; url=../stable/api.html"/>
"""
    @test files["stable/api.html"] == """<!--This file is automatically generated by docs/deploy.jl-->
<meta http-equiv="refresh" content="0; url=../v2.2.1/api.html"/>
"""
    @test files["stable/index.html"] == """<!--This file is automatically generated by docs/deploy.jl-->
<meta http-equiv="refresh" content="0; url=../v2.2.1/"/>
"""

    @test sort(collect(keys(files))) == [
        "api.html",
        "api/index.html",
        "examples.html",
        "examples/index.html",
        "stable/api.html",
        "stable/examples.html",
        "stable/index.html",
    ]
    @test collect(files) == collect(stable_redirect_files(reverse(pages), "v2.2.1"))
    root_stubs = filter(((path, _),) -> !startswith(path, "stable/"), files)
    @test all(!occursin(r"v\d", content) for content in values(root_stubs))
end

@testset "stale redirects" begin
    files = stable_redirect_files(["api"], "v2.2.1")
    root_stubs = filter(((path, _),) -> !startswith(path, "stable/"), files)

    root = mktempdir()
    for (path, content) in root_stubs
        mkpath(joinpath(root, Base.dirname(path)))
        write(joinpath(root, path), content)
    end
    # A page dropped since the previous release, in both of its stub forms.
    for (path, content) in stable_redirect_files(["gone"], "v2.2.0")
        startswith(path, "stable/") && continue
        mkpath(joinpath(root, Base.dirname(path)))
        write(joinpath(root, path), content)
    end
    # Everything a deployment leaves at the root besides our stubs.
    write(joinpath(root, "index.html"), "<!--This file is automatically generated by DocumenterVitepress.jl-->\n")
    write(joinpath(root, "versions.js"), "var DOC_VERSIONS = [];\n")
    for version in ("v2.2.1", "dev", "stable")
        mkpath(joinpath(root, version))
        write(joinpath(root, version, "index.html"), "<!DOCTYPE html>\n")
    end
    write(joinpath(root, "stable", "index.html"), files["stable/index.html"])

    @test stale_root_stubs(root, keys(root_stubs)) == ["gone.html", "gone/index.html"]
    @test isempty(stale_root_stubs(root, keys(stable_redirect_files(["api", "gone"], "v2.2.1"))))
end
